###################################################
#
# Makefile
# Author: Methodios Zacharioudakis
#
###################################################

all: crypto

crypto: crypto.c crypto.h
	gcc -o crypto crypto.c

clean:	rm -f crypto
	clear